CREATE TABLE CUSTOMERS (
    CUSTOMERID   NUMBER PRIMARY KEY,
    CUSTOMERNAME VARCHAR2(50),
    AGE          NUMBER,
    BALANCE      NUMBER(10, 2),
    ISVIP        VARCHAR2(5)
);

CREATE TABLE LOANS (
    LOANID       NUMBER PRIMARY KEY,
    CUSTOMERID   NUMBER,
    INTERESTRATE NUMBER(5, 2),
    DUEDATE      DATE,
    FOREIGN KEY ( CUSTOMERID )
        REFERENCES CUSTOMERS ( CUSTOMERID )
);